<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macro.xacro" />
    <xacro:include filename="gazebo_control.xacro" />
    <!-- <xacro:include filename="ros2_control.xacro" />  -->
    <xacro:include filename="lidar.xacro" />
    <xacro:include filename="camera.xacro" />
   <!-- <xacro:include filename="imu.xacro" /> -->

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="gray">
        <color rgba="0.52 0.52 0.52 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>   

    <!--Define robot constants-->
    <xacro:property name = "base_width" value="0.3"/>
    <xacro:property name = "base_height" value="0.1"/>
    <xacro:property name = "base_length" value="0.4"/>

    <xacro:property name = "wheel_radius" value="0.06"/>
    <xacro:property name = "wheel_width" value="0.04"/>
    <xacro:property name = "wheel_ygap" value="0.025"/>
    <xacro:property name = "wheel_zoff" value="0.03"/>
    <xacro:property name = "wheel_xoff" value="0.15"/>

    <!--Robot Footprint-required for navigation to get robot center-->
    <link name="base_footprint">
    </link>

    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <!--Robot base-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box 
            mass="15" y="${base_width}" z="${base_height}" x="${base_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect pitch axis">

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_footprint"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${wheel_zoff}" rpy="${pitch*pi/2} 0 0"/>
            <axis xyz="0 0 ${axis}"/>
        </joint>

        <link name="${prefix}_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder
                mass="0.5" radius="${wheel_radius}" length="${wheel_width}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
        <gazebo reference="${prefix}_link">
            <material>Gazebo/Gray</material>
        </gazebo>
        
    </xacro:macro>

    <xacro:wheel prefix="front_lwheel" x_reflect="1" y_reflect="1" pitch="-1" axis="1"/>
    <xacro:wheel prefix="front_rwheel" x_reflect="1" y_reflect="-1" pitch="1" axis="-1"/>
    <xacro:wheel prefix="rear_lwheel" x_reflect="-1" y_reflect="1" pitch="-1" axis="1"/>
    <xacro:wheel prefix="rear_rwheel" x_reflect="-1" y_reflect="-1" pitch="1" axis="-1"/> 


</robot>